name: Daily Scraper

on:
  schedule:
    - cron: "0 7 * * *"      # Every day at 07:00 UTC
  workflow_dispatch:         # Allow manual run

permissions:
  contents: write

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip xvfb

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Setup directories
        run: |
          mkdir -p text_storage
          mkdir -p /tmp/chrome-user-data
          chmod 755 /tmp/chrome-user-data

      - name: Run daily scraper
        run: |
          python daily_scraper.py

      - name: Commit changes
        id: commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add changes.md text_storage
          if git diff --staged --quiet; then
            echo "no_changes=true" >> $GITHUB_OUTPUT
          else
            git commit -m "🔄 Daily scrape update: $(date -u '+%Y-%m-%d %H:%M:%S') UTC"
            git push
            echo "no_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Send Telegram notification
        if: steps.commit.outputs.no_changes == 'false'
        run: |
          # Read the changes.md file
          CHANGES_CONTENT=$(cat changes.md)
          
          # Function to send Telegram message
          send_telegram_message() {
            local message="$1"
            curl -s -X POST \
                 "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
                 -H "Content-Type: application/json" \
                 -d "{
                   \"chat_id\": \"${{ secrets.TELEGRAM_CHAT_ID }}\",
                   \"text\": \"$message\",
                   \"parse_mode\": \"HTML\"
                 }"
          }
          
          # Send header message
          TIMESTAMP=$(date -u '+%Y-%m-%d %H:%M:%S')
          HEADER_MESSAGE="🔄 <b>Daily Scraper Update</b>\n\n<i>Updated at: $TIMESTAMP UTC</i>\n\n---"
          send_telegram_message "$HEADER_MESSAGE"
          
          # Split content into chunks of max 4000 characters (safe for Telegram)
          MAX_LENGTH=4000
          CURRENT_CHUNK=""
          CHUNK_NUMBER=1
          
          # Read changes.md line by line and build chunks
          while IFS= read -r line; do
            # If adding this line would exceed max length, send current chunk and start new one
            if [ ${#CURRENT_CHUNK} -gt 0 ] && [ $((${#CURRENT_CHUNK} + ${#line} + 50)) -gt $MAX_LENGTH ]; then
              # Send current chunk
              send_telegram_message "$CURRENT_CHUNK"
              CURRENT_CHUNK=""
              CHUNK_NUMBER=$((CHUNK_NUMBER + 1))
              sleep 1  # Small delay between messages
            fi
            
            # Add line to current chunk
            if [ ${#CURRENT_CHUNK} -eq 0 ]; then
              CURRENT_CHUNK="<b>Part $CHUNK_NUMBER:</b>\n\n$line"
            else
              CURRENT_CHUNK="$CURRENT_CHUNK\n$line"
            fi
          done < changes.md
          
          # Send the last chunk if there's anything left
          if [ ${#CURRENT_CHUNK} -gt 0 ]; then
            send_telegram_message "$CURRENT_CHUNK"
          fi
          
          # Send footer message
          FOOTER_MESSAGE="---\n✅ <b>Scraping completed!</b>\n\n<i>Check the repository for the complete changes.md file</i>"
          send_telegram_message "$FOOTER_MESSAGE"


